language: perl
script:
  - "perl Build.PL"
  - "./Build"
  - "env AUTHOR_TESTING=1 ./Build test"
install:
  - "cpanm --with-recommends --installdeps --notest ."
notifications:
  email:
    - anazawa@cpan.org
branches:
  only:
    - master
